### ISSUE TITLE
SvPileup writes a query-grouped BAM, but AggregateSvPileup requires a coordinate sorted and index BAM

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fgsv#15]
This is not clarified in the AggregateSvPileup documentation

**Comment by tfenne** [comment]
`AggregateSvPileup` wants the same set of reads that were fed _into_ `SvPileup`, not it's output.  However the documentation is still wrong - it says is must be the same BAM file as used in `SvPileup`, when what it should say is the same BAM file, _except in coordinate sort order_.
