### ISSUE TITLE
SvPileup should handle circular contigs better

### ISSUE THREAD

**Issue by tfenne** [fulcrumgenomics/fgsv#24]
When running SvPileup on a BAM file aligned carefully to a circular genome (plasmid, mito) it generates:

1. A really well supported breakpoint using split-reads than span the origin
2. A _huge_ number of "abnormal pair" supported breakpoints

For intra-contig evidence, if the contig is labeled as circular (`TP:circular` in the relevant `SQ` header), sv-pileup should treat the transition around the origin as contiguous and re-calculate the "inner distance" between segments for split reads and between reads for pairs.  Doing this should remove the vast majority of origin-related breakpoints being emitted.

**Comment by jdidion** [comment]
Do you have some example data I can use for test case(s)?
